#!/usr/bin/env bash

set -euo pipefail

if [ "${#}" != 1 ]; then
	(
		echo "Usage: ${0} <connectTo>"
		echo
		echo 'connectTo is an SSH connection string'
	) >&2
	exit 1
fi

nix build --builders '' -f '<nixpkgs/nixos>' -I nixos-config=./configuration.nix config.system.build.kexec_tarball

connectTo="${1}"
ssh="ssh ${connectTo}"

if ! ${ssh} echo Connection successful; then
	echo "Connection cannot be established"
	exit 1
fi

# Prepare tmpfs
${ssh} mkdir -p /nix /tmp
${ssh} mount -t tmpfs tmpfs /tmp
${ssh} mkdir -p /tmp/work /tmp/nix

# Install rsync
${ssh} "apt-get update -q || apt-get update -q || echo 'apt-get update failed twice but continuing anyway'"
${ssh} "env DEBIAN_FRONTEND=noninteractive apt-get --quiet --assume-yes --no-install-recommends install rsync"

# Copy and extract
rsync -P result/tarball/*.xz "${connectTo}:/tmp/emergency.tar.xz"
${ssh} tar xf /tmp/emergency.tar.xz -C /tmp
# Overlay the second /nix
${ssh} mount -t overlay overlay -o lowerdir=/nix,upperdir=/tmp/nix,workdir=/tmp/work /nix
# Here goes nothing
${ssh} /tmp/kexec
